[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AESB2122_project"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["."] 
include = ["AESB2122_project*"] 
exclude = ["images*", "tests*", "build*", "dist*"]